using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PoolApp1
{
    public class Schedule
    {
        public string City { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Pool { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string Href { get; set; }
        public string Program { get; set; }
        public DayOfWeek DayOfWeek { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public TimeSpan Duration { get { return EndTime - StartTime; } }

        public static List<Schedule> Schedules = new List<Schedule>() {
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Single lane swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(9, 00, 00), EndTime= new TimeSpan(10, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Single lane swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Single lane swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(9, 00, 00), EndTime= new TimeSpan(10, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Single lane swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(9, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(12, 00, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(20, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(9, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(12, 00, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(20, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(9, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(12, 00, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(9, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(9, 00, 00), EndTime= new TimeSpan(10, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Public swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(18, 30, 00), EndTime= new TimeSpan(20, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Centennial Pool", Lat= 43.522536, Lon= -80.247808, Href= "http=//guelph.ca/living/recreation/rec-facilities/centennial-pool/", Program= "Women\'s only swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(13, 30, 00), EndTime= new TimeSpan(15, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Lane swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(9, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Lane swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(9, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(6, 30, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(6, 30, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "50-metre fitness swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(12, 30, 00), EndTime= new TimeSpan(13, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Public swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Public swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(11, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(21, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(21, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(21, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "Victoria Road Recreation Centre", Lat= 43.563825, Lon= -80.238879, Href= "http=//guelph.ca/living/recreation/rec-facilities/victoria-road-recreationcentre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(21, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(6, 15, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(6, 15, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(11, 45, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(21, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(6, 15, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(8, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Fitness swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Public swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(19, 30, 00), EndTime= new TimeSpan(21, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Public swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Public swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(13, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Leisure swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 55, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 55, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(14, 00, 00), EndTime= new TimeSpan(15, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 30, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(15, 45, 00), EndTime= new TimeSpan(16, 45, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(7, 00, 00), EndTime= new TimeSpan(8, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Friday, StartTime= new TimeSpan(10, 30, 00), EndTime= new TimeSpan(11, 55, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Saturday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Family Friendly Warm Waters Swim", DayOfWeek= DayOfWeek.Sunday, StartTime= new TimeSpan(13, 00, 00), EndTime= new TimeSpan(14, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Monday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Tuesday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Wednesday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
            new Schedule { City = "Guelph", StartDate= new DateTime(2017, 9, 5), EndDate= new DateTime(2018, 3, 31), Pool= "West End Community Centre", Lat= 43.524788, Lon= -80.291882, Href= "http=//guelph.ca/living/recreation/rec-facilities/west-end-community-centre/", Program= "Soothing waters swim", DayOfWeek= DayOfWeek.Thursday, StartTime= new TimeSpan(20, 00, 00), EndTime= new TimeSpan(22, 00, 00) },
        };
    }
}
